CMakeLists.txt
xdgaction.h
xdgautostart.h
xdgdesktopfile.h
xdgdirs.h
xdgicon.h
xdgmacros.h
xdgmenu.h
xdgmenuwidget.h
xdgmime.h
xdgmimetype.h
xmlhelper.h

This greatly reduced the size of dynamic symbol table and might potentially speed up loading.
Also, turn off exception handling to save more since we don't use it.
For non-gcc compilers, this change does nothing.
@luis-pereira please see if this is OK for you. :-)
Thanks!

Use gcc visibility attribute and Q_DECL_EXPORT macro to avoid exporting internal symbols.

---

qiconfix/qiconloader.cpp
qiconfix/qiconloader_p.h

Port  QIconLoader/QIconLoaderEngine's development to our "fixed" versions.
* It improves performance. Mainly due to https://github.com/lxde/libqtxdg/commit/0940e8a7e89f58686a7c0275cf2331c4e9759d78
* https://github.com/lxde/libqtxdg/commit/3b2b71bef46d3565db921c6a943c83ac0e8926b0 It avoids setting an empty parent theme. Needed to properly handle the latest breeze (plasma, at least) icon themes.
* Minor improvements and housekeeping stuff.
I'm using it with Qt 5.4 without any problems and noticed performance gains in icon intensive tasks  e,g https://github.com/lxde/lxqt/issues/467 and https://github.com/lxde/lxqt-config/pull/38
@surlykke  @paulolieuthier @PCMan @agaida @kuzmas @SokoloffA @jleclanche It would be nice that that you guys tested it. Specially with Qt 5.3, that I don't have at …

Sync qiconloader

---

CMakeLists.txt

There are two install components:
* Devel Contains all the development files;
* Runtime Contains all the runtime needed files.
It's possible to install:
- Everything: make install OR cmake -P cmake_install.cmake
- Development files only: cmake -DCOMPONENT=Devel -P cmake_install.cmake
- Runtime files only: cmake -DCOMPONENT=Runtime -P cmake_install.cmake
This COMPONENT's can also be used with CPack.

CMake: Adds Runtime install COMPONENT

---

xdgdesktopfile.h

It was missing and helps writing more easily understandable code in some
situations.

Adds XdgDesktopFile != operator

---

xdgdesktopfile.cpp

it is an optional enty of the specification [1]
http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>

xdgdesktopfile: handle 'Path' entry for application's working directory

---

xdgdirs.cpp

If the path to the folder is empty we return the default value.
It's what xdg-user-dirs also do.

XdgUserDirs: Return a fallback when the path is empty

---

qiconfix/qiconloader.cpp

If the scalable icon (.svg) is found in directory not marked as
scalable, the actualSize() will always return {0,0}. This in turn will
break showing this icon in many Qt widgets/views (actualSize() is used
to determine the sizeHint() etc.).
closes lxde/lxqt#976

iconloader: Fix actualSize() for scalable icons

---

CMakeLists.txt
util/CMakeLists.txt
util/qtxdg-desktop-file-start.cpp

It allows a developer to start an .desktop file from the command line.
Closes #63.

Adds an .desktop file start tester

---

xdgdesktopfile.cpp

We fallback to use the Exec key when the DBusActivatable fails.
Closes lxde/lxqt#967.

XdgDesktopFile: Adds Exec fallback when DBusActivatable fails

---

xdgdesktopfile.cpp
xdgdesktopfile.h

It implements the desktop-file ID calculator.
Spec:
https://specifications.freedesktop.org/desktop-entry-spec/latest/ape.html

XdgDesktopFile: Adds a Desktop File ID calculator method

---

qtxdg/xdgdesktopfile.cpp
qtxdg/xdgdirs.cpp

Avoids unnecessary string conversions.

qtxdg: Get the HOME environment variable just one time

---

qtxdg/xdgdesktopfile.cpp

Explicitly initialize all members.

XdgDesktopFileData: Explicitly initialize members

---

CMakeLists.txt
xdgiconloader/CMakeLists.txt

It was an implicit dependency as XdgIconLoader always support svg icons.
Let's make it explicit.

Adds Qt5Svg explicitly to the required packages

---

xdgiconloader/xdgiconloader.cpp

It was always returning true.
Closes lxde/libqtxdg#98.
Closes lxde/lxqt#1081.

Fixes QIcon::hasThemeIcon() behaviour with our Icon Loader Engine

---

README.md

Adds gtk-update-icon-cache to the optional runtime dependencies.

Updates dependencies

---

CMakeLists.txt
qtxdg/xdgicon.cpp
qtxdg/xdgicon.h
xdgiconloader/xdgiconloader.cpp
xdgiconloader/xdgiconloader_p.h

1. Use as much of the Qt QIconLoader implementation as possible (do not
just copy-paste all of the logic from Qt sources).
2. Do not store the currently set theme name in XdgIconLoader instance,
but reuse the underlying QIconLoader for it.
With this change there is only one place where the current theme (name,
paths, etc.) is stored => the calls XdgIcon::\*themeName and
QIcon::\*themeName are interchangable.
TODO: deprecate and/or remove the XdgIcon & XdgIconLoader wrapper
functions (which only call QIcon & QIconLoader functions).

[WIP] qiconloader: Reuse Qt implementation

---

xdgiconloader/xdgiconloader.cpp

We can't assume, that the first found scalable entry is the only and
best one and stop searching.
This was an false (over)optimization or a failed merge of upstream Qt
patches.
fixes #122

xdgiconloader: Consider all existing files/images

---

xdgiconloader/xdgiconloader.cpp

Return an empty size if no suitable entry found to avoid mismatch
with the returned `pixmap()`'s size (the `QIconEngine::actualSize()` returns
the originally requested size).
closes lxde/lxqt#1282

xdgiconloader: Fix XdgIconLoaderEngine::actualSize()

---

xdgiconloader/xdgiconloader.cpp
xdgiconloader/xdgiconloader_p.h

This is my idea of a *practically* correct hierarchy of fallbacks, in contrast to what XDG specification tells us.
The icon is searched in the theme *and all of its parents*. Then, if it is not found, the search is done for the first "dash fallback" in the theme and all of its parents. And so on for the second, third,... "dash fallbacks".
Anyone has right to hate this but I use it to have acceptable fallback icons under LXQt, in the same way I have them under KDE.

Correct hierarchy of fallbacks

---

xdgiconloader/xdgiconloader.cpp
xdgiconloader/xdgiconloader_p.h

The hicolor theme is the ultimate resort. It should be allowed only at the
end of the fallback hierarchy. We are allowing the hicolor theme to be in
the middle of the theme hierarchy. Schematically:
X -> hicolor -> Y -> Z -> hicolor
If an icon exists in the hicolor and Y theme the hicolor one, is wrongly
used.
This commit does four things:
* Stops adding the hicolor theme to each theme as a fallback.
* Stops adding the hicolor as a parent theme, even if added by the
index.theme Inherits key. The oxygen theme does it.
* Stops return the hicolor theme in the fallbackTheme().
* Adds the hicolor theme to the end of the fallback hierarchy list.

xdgiconloader: Puts the hicolor at the end of the theme hierarchy

---

qtxdg/CMakeLists.txt
qtxdg/xdgaction.h
qtxdg/xdgautostart.cpp
qtxdg/xdgdesktopfile.cpp
qtxdg/xdgdirs.cpp
qtxdg/xdgicon.cpp
qtxdg/xdgmenu.cpp
qtxdg/xdgmenu.h
qtxdg/xdgmenu_p.h
qtxdg/xdgmenuapplinkprocessor.cpp
qtxdg/xdgmenureader.cpp
qtxdg/xdgmenureader.h
qtxdg/xdgmimetype.cpp
test/CMakeLists.txt
test/qtxdg_test.cpp
test/qtxdg_test.h
test/tst_xdgdesktopfile.h
test/tst_xdgdirs.cpp
util/CMakeLists.txt
xdgiconloader/CMakeLists.txt
xdgiconloader/plugin/CMakeLists.txt

Use Q_ macros instead of signals, slots, emit, foreach... to increase
compatibility with other libraries (Boost, GLib, etc).

Avoid Qt special keywords collision

---

qtxdg/xdgautostart.cpp
qtxdg/xdgdesktopfile.cpp
qtxdg/xdgdirs.cpp
qtxdg/xdgicon.cpp
qtxdg/xdgmenu.cpp
qtxdg/xdgmenuapplinkprocessor.cpp
qtxdg/xdgmenureader.cpp
qtxdg/xdgmimetype.cpp
test/qtxdg_test.cpp

Qt 5.9 deprecated it. Replaced with C++11 ranged for-loops.
We don't use qAsConst(). It was introduced in Qt 5.7. We don't require
Qt 5.7. qAsConst() replaced with const_cast<const T&>(t).

Drop Q_FOREACH

---

xdgiconloader/xdgiconloader.cpp
xdgiconloader/xdgiconloader_p.h

QIconLoader original commit:
http://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/image?id=f299b565b5904e39a47b6133643448e46810f0ed
Implement support for Scale directory key according to Icon Theme spec
Qt already supports high DPI icons using the “@nx” approach, where the
device pixel ratio that the image was designed for is in the file
name. However, our implementation of the freedekstop.org Icon Theme
specification did not support the Scale directory key:
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout
This meant that users creating icons via QIcon::fromTheme() did not
get high DPI support. This patch fixes that.
[ChangeLog][QtGui][QIcon] Implemented support for Scale directory key
according to Icon Theme Spec. Icons created via …

Backport support for Scale directory key according to Icon Theme spec

---

qtxdg/xdgdesktopfile.cpp

According to latest spec [https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html) (currently v1.0.1), there is a new list of directories to look for mimeapps.list file.
Also fix reading and writing mimeapps.list files to allow properly writing elements containing multiple values (and reading it back).

Use new mimeapps.list directories

---

qtxdg/xdgdesktopfile.cpp

QObject::connect() brings a severe performance penalty when not using
normalized signatures. Signal lookup is first attempted with the signature
as-is, and if that fails QMetaObject::normalizedSignature() called.
That means, when using non-normalized signal/slot signatures, you not only
pay for a strcpy(), but also for a doomed-to-fail first lookup attempt.
Sure, connects are usually done during startup, and a profiler won’t show
you, but using non-normalized signatures is hereby firmly put into the
realm of premature pessimisation.
Reference:
https://marcmutz.wordpress.com/effective-qt/prefer-to-use-normalised-signalslot-signatures/

Normalize signal/slot signatures

---

xdgiconloader/xdgiconloader.cpp
xdgiconloader/xdgiconloader_p.h

..by using the QSvgIconEngine under the hood.
This was done previously in be58584d0e6c11feaa6929099885ff2a7d882401,
but was reverted by 81e6ffa52ff2ec6d6bcff7e936b6a7fe04c5bbdb (this
completely lacks any caching and does read/process file and generate
image for each pixmap() call).
In this commit we don't create the (private) QSvgIconEngine manually,
but use the operators <<, >> to achieve it. Thus reducing the chance
to break things with future Qt versions (the (de)serialization will
never change for requested QDataStream::Version).

xdgiconloader: Cache ScalableFollowsColorEntry properly

---

xdgiconloader/xdgiconloader.cpp

In case an icon is added and the GTK cache is refreshed the already
running Qt application does not get the information from GTK cache.
That's because the cache file is changed (modified or deleted+newly
created), but the mapped memory used to read the file is not affected.
We will re-map the cache file for such situations to properly use the
cache also after the content change.

xdgiconloader: Add GTK cache revalidation

---

qtxdg/xdgaction.cpp

..as it can lead to unwanted recurrency and cause segfaults.
E.g.: lxqt-panel mainmenu searching:
(0x7ffe4effb0e0) Warning: QWidget::repaint: Recursive repaint detected
(0x7ffe4effb0e0) Warning: QWidget::paintEngine: Should no longer be called
(0x7ffe4effb0e0) Warning: QPainter::begin: Paint device returned engine == 0, type: 1
(0x7ffe4effb0e0) Warning: QPainter::save: Painter not active
(0x7ffe4effb0e0) Warning: QPainter::setPen: Painter not active
(0x7ffe4effb0e0) Warning: QPainter::drawRects: Painter not active
(0x7ffe4effb0e0) Warning: QPainter::restore: Unbalanced save/restore

xdgaction: Remove unneeded processEvents() call

---

src/qtxdg/xdgmacros.h

It reduces the clutter. Ex: instead of writing:
```if (node.hasAttribute(QStringLiteral("http-contents-length")))```
just write:
```if (node.hasAttribute(QSL("http-contents-length")))```

Adds Qt Strings abbreviations macros

---

src/xdgiconloader/xdgiconloader.cpp

In our support for KDE symbolic icons, we only considered `.ColorScheme-Text`. But some Breeze symbolic icons use KDE-specific schemes like `.ColorScheme-NegativeText`. Of course, we don't use such colors but even `.ColorScheme-Text` is something we've taken from KDE (it could be any string otherwise). So, it's better to cover all KDE text colors but set all of them to the same color.
Without this patch, some Breeze icons with KDE-specific schemes (like the 16-px `window-close.svg` or `application-exit.svg`) would always be pitch black -- even with dark Qt styles -- because their schemes are erased. But with this patch, they are like other icons: light on dark backgrounds and dark on light ones.
In short, this is needed if we want KDE icon sets to be really usable under LXQt too.

Cover all KDE colors schemes for symbolic icons

---

src/xdgiconloader/xdgiconloader.cpp

We now the variables are not used.

Silent compiler warnings

---

src/qtxdg/CMakeLists.txt
src/qtxdg/dbus/org.freedesktop.Application.xml
src/qtxdg/xdgdesktopfile.cpp

For case when the DBusActivatable application is unresponsive the
startDetached() can block for a long time (the Qt default 25s DBus
timeout). Blocking can't be avoided while using QDBusInterface, because
the object can block directly in its contructor.
So we use the generated interface class and set the timeout for the DBus
call to 1500ms (can be overriden env variable QTXDG_DBUSACTIVATE_TIMEOUT).
See also: https://bugreports.qt.io/browse/QTBUG-75016
fixes #181

xdgdesktopfile: Avoid freeze for DBusActivatable apps

---

src/qtxdg/xdgdesktopfile.cpp

QRegularExpression is recommended over QRegExp.
QRegularExpression has Perl compatible syntax and performs a lot better.

Drop QRegExp.

---

cmake/compiler_settings.cmake

They are globally set in LXQtCompilerSettings.

CMake: Remove string conversion flags

---

src/qtxdg/xdgmenureader.cpp

Missed this one. Don't know how.

Prevent a c++11 range-loop possible detach

---

src/xdgiconloader/xdgiconloader.cpp

Qt already removed qt_cocoa_helpers_mac_p.h and qt_mac_get_scalefactor().

XdgIconLoader: Remove dead Qt4 Mac code

---

src/qtxdg/xdgmimetype.h

Reverts lxqt/libqtxdg#197
Breaks building of lxqt-panel and lxqt-config with Qt 5.14 and GCC 9.2 on Arch Linux.

Fix XdgMimeType with Qt 5.14

---

src/qtxdg/xdgmimetype.cpp
src/qtxdg/xdgmimetype.h

Commit 6f597b30cef2bdefc9ca5362cdf195294ebb9556 replaced qSwap() with
std::swap(). It caused a FTBFS with Qt5.14
Commit c6b89c7af127d49739c9d2d9d323c931c509dcaa fixed it.
But it can be made to work with std::swap(), which is more readable, and
resilient to changes in Qt internals.
Tested with Qt5.14.2 and Qt5.14.1

Use std::swap()

---

src/qtxdg/xdgdesktopfile.cpp
src/qtxdg/xdgdirs.cpp
src/xdgiconloader/xdgiconloader.cpp

Silent warnings about non-POD global statics. They are known.
Multi-line declarations confuses clazy parser so we apply it to the whole
file.

Silent known clazy warnings

---

src/qtxdg/xdgmenuapplinkprocessor.cpp
src/qtxdg/xdgmenuapplinkprocessor.h
src/qtxdg/xdgmenulayoutprocessor.cpp
src/qtxdg/xdgmenurules.cpp
src/qtxdg/xmlhelper.h

When an object of a class is created, the constructors of all member
variables are called consecutively in the order the variables are declared,
even if we don't explicitly write them to the initialization list.

Move member initialization to the initialize list

---

src/qtxdg/xdgmimeappsglibbackend.cpp

Hopefully, they were the last ones. I found them only indirectly and with `valgrind`; they weren't easy to find, especially for the original programmer and during coding.

Fixed further memory leaks.

---

src/qtxdg/xdgmimeappsglibbackend.cpp

In LXQt, although the GLib backend reads `~/.config/lxqt-mimeapps.list`, it writes to `~/.config/mimeapps.list` on setting default apps. Since we want to set default apps only for LXQt, the patch directly writes them to `lxqt-mimeapps.list` — after adding the needed associations to `mimeapps.list` (GLib always does the latter).
The patch considers `XDG_CURRENT_DESKTOP` and works outside LXQt too. In other words, it isn't limited to `lxqt-mimeapps.list`.
Fixes https://github.com/lxqt/libqtxdg/issues/218

Fixed setting of default apps with GLib backend

---

src/xdgiconloader/xdgiconloader.cpp

Backport of commit:
https://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/image/qiconloader.cpp?id=98c5f22161e25c0f6867c0bf7db7aa8d6fcf6074

Avoid invalid memory access in QIconCacheGtkReader::lookup()

---

src/qtxdg/xdgdefaultapps.cpp

Using conditional compilation to avoid warnings with Qt versions >=Qt5.14.
Fixes https://github.com/lxqt/libqtxdg/issues/230.

Fix a FTBFS with Qt versions earlier than 5.14

---

src/xdgiconloader/xdgiconloader.cpp

Qt6 dropped QStringRef.
Note: QStringViews should be passed by value, not by reference-to-const.
Passing a reference-to-const, compiles and works, but is slower.

Port QStringRef to QStringView

---

src/qtxdg/xdgmenurules.cpp
src/tools/mat/defemailclientmatcommand.cpp
src/tools/mat/deffilemanagermatcommand.cpp
src/tools/mat/defwebbrowsermatcommand.cpp
src/xdgiconloader/xdgiconloader.cpp

Use empty() instead of size() is easier to understand.
Also avoids an implicit cast.

Improve readability in container emptiness check

---

src/qtxdg/xdgaction.cpp
src/qtxdg/xdgmenu.cpp
src/qtxdg/xdgmenu_p.h

Just one notable change. I had to set the public inheritance of XdgMenuPrivate from QObject. It doesn't work otherwise. Anyway I coudn't find one reason why it has to privately inherit.

Move to Qt5 signal/slot syntax

---

CMakeLists.txt

A quick mitigation to https://github.com/lxqt/lxqt/issues/1889.
Note to packagers: Add XTerm as a recommended dependency.

Add XTerm as a runtime dependency

---

src/qtxdg/xdgmenu.cpp

A local variable shouldn't shadow a outer variable.

Don't shadow variables

---

src/qtxdg/xdgdesktopfile.cpp

Allow runtime overriding of detachment of processes by setting the
QTXDG_START_DETACH_TRULY. Default value is true [1].
With this the application (using libqt5xdg) can correctly send
termination signal to child processes on the application exit.

xdgdesktopfile: Allow non-detach starting

---

src/xdgiconloader/xdgiconloader.cpp

`QSvgRenderer` is used with a cache for both ordinary and colorized SVG icons. In this way, LXQt's icon handling cannot be broken by intruding icon engines, which register themselves for "svg" (see https://github.com/lxqt/libqtxdg/issues/246). Moreover, it does not depend on a specific code structure of `qtsvg` or any other icon engine.

Use QSvgRenderer for SVG icons

---

src/xdgiconloader/xdgiconloader.cpp

QStringView was introduced in Qt 5.10 but some methods were introduced in
later versions. QStringView::lastIndexOf() was introduced in Qt 5.14.
Fixes https://github.com/lxqt/libqtxdg/issues/250.

Fix a QStringView related FTBFS

---

src/xdgiconloader/xdgiconloader.cpp

It may not be needed in practice but Qt does it in `qicon.cpp` → `QPixmapIconEngine::paint()`.

Added a nullity check for paint device

---

src/qtxdg/xdgmenuwidget.cpp

When starting drag, it should get the action that was clicked instead of the action currently under the cursor when qt detects drag action.
Causes issues in `lxqt-panel/plugin-mainmenu` when dragging items to quicklaunch or desktop, causing the adjacent item to be dragged instead.

XdgMenuWidget: fix for sometimes dragging incorrect action

---

src/xdgiconloader/xdgiconloader.cpp

Dash fallbacks can cause all sorts of troubles. Although the inherited themes were searched *before* them, the code first ignored `hicolor` among the inherited themes and then searched it *after* dash fallbacks. That's corrected by the current patch.
Fixes https://github.com/lxqt/libqtxdg/issues/260. That report is also an example of how annoying dash fallbacks could be if they aren't used *only* as the last resort.

Make sure `hicolor` is searched before dash fallbacks

---

src/tools/mat/qtxdg-mat.cpp

An asked --help must return EXIT_SUCCESS.
Any option passed to an non existent module must return EXIT_FAILURE.

qtxdg-mat: Rework exit codes

---

src/tools/mat/defappmatcommand.cpp
src/tools/mat/defemailclientmatcommand.cpp
src/tools/mat/deffilemanagermatcommand.cpp
src/tools/mat/defterminalmatcommand.cpp
src/tools/mat/defwebbrowsermatcommand.cpp
src/tools/mat/mimetypematcommand.cpp
src/tools/mat/openmatcommand.cpp
src/tools/mat/qtxdg-mat.cpp

Wasn't being handled.
Just a documentation error, or a shortcoming in the API.
Upstream Qt bug description: https://bugreports.qt.io/browse/QTBUG-92567

qtxdg-mat: Handle '--help-all' option

---

src/qtxdg/xdgdesktopfile.cpp

It is assumed that a string literal starts with a non-escaped, non-quoted single/double quote and ends with the next single/double quote. This assumption is made based on the behavior of `GLib`, as reflected by `pcmanfm-qt` (→ `libfm-qt`).
The parameters and EVs are not expanded inside string literals.
Closes https://github.com/lxqt/lxqt-panel/issues/1705

Support string literals in Exec keys of desktop entries

---

src/qtxdg/xdgdefaultapps.cpp

Previously, it started with dash.
See https://github.com/lxqt/libfm-qt/pull/766 for a similar fix.

Fixed config file name with empty `XDG_CURRENT_DESKTOP`

---

src/qtxdg/xdgmenureader.cpp

Quoting https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html: "The default locations that are earlier in the search path go later in the `<Menu>` so that they have priority".

Follow `freedesktop.org` in adding dirs under `DefaultDirectoryDirs`

---

util/qtxdg-iconfinder.cpp

Adapt to:
using QThemeIconEntries = std::vector<std::unique_ptr<QIconLoaderEngineEntry>>;

qtxdg-iconfinder: Fix an FTBFS

---

src/qtxdg/xdgmenu.cpp

Recently, `applications.menu` (belonging to `kservice5`) was removed and `plasma-applications.menu` (belonging to `plasma-workspace`) was added. Hence adding the latter to the fallback list.

Added `plasma-applications.menu` to fallback menu files

---

src/xdgiconloader/xdgiconloader.cpp
src/xdgiconloader/xdgiconloader_p.h

Adapt to changes in private headers Qt v6.9

---

CMakeLists.txt
src/qtxdg/CMakeLists.txt
src/xdgiconloader/CMakeLists.txt
src/xdgiconloader/plugin/CMakeLists.txt

The 'Qt6FooPrivate' targets have been split into separate CMake files
in Qt 6.9, and require a 'find_package(Qt6FooPrivate)' call starting
with Qt 6.10.
See also: https://bugreports.qt.io/browse/QTBUG-87776

cmake: fix build with Qt 6.10
