lxqt/libqtxdg

- xdgmime.h
Signed-off-by: Helio Chissini de Castro <helio@kde.org>
> - Fix compilation when using internal mime

- xdgdirs.cpp
> Fix missing slash in paths in xdgDirList

- xdgdesktopfile.cpp
> desktopfile: run new process as a direct child

- desktopenvironment_p.cpp
- test/qtxdg_test.cpp
- test/qtxdg_test.h
- xdgdesktopfile_p.h
> added missing licensing headers

- xdgdesktopfile.cpp
Based on Qt doc:
'Note: when dealing with remote objects, it is not always possible to
determine if it exists when creating a QDBusInterface.'
The QDBusAbstractInterface::lastError() seems to be more appropriate.
> desktopfile: Change validity check

- xdgdesktopfile.cpp
- xdgdesktopfile.h
A convenience, but handy, member.
> Adds XdgDesktopFile::mimeTypes() member

- xdgautostart.cpp
- xdgdirs.cpp
- xdgicon.cpp
- xdgmenu.cpp
- xdgmenuapplinkprocessor.cpp
- xdgmenureader.cpp
- xdgmimetype.cpp
We use const references where appropriate. Also made the container constant
when appropriate.
> Improve foreach iteraror performance

- qtxdg/xdgdesktopfile.cpp
- qtxdg/xdgdesktopfile.h
They are deprecated for a long time now.
> XdgDesktopFile: Removes deprecated members

- qtxdg/xdgdesktopfile.cpp
Very easy to do, but, hard to spot.
> XdgDesktopFileCache: Fixes an coding typing error

- qtxdg/xdgdesktopfile.cpp
> xdgdesktopfile: Removes double QLatin1String's contruction

- test/CMakeLists.txt
- test/tst_xdgdesktopfile.cpp
- test/tst_xdgdesktopfile.h
Test some (not all, yet) of it.
> XdgDesktopFile: Adds tests

- xdgiconloader/xdgiconloader.cpp
Upstream qiconloader ports.
https://github.com/lxde/libqtxdg/commit/44524bdb1060afd18903edd25afd12b69114363b brings some performance improvement.
> Xdgiconloader maint

- util/CMakeLists.txt
- util/qtxdg-iconfinder.cpp
It helps testing and evaluating https://github.com/lxde/libqtxdg/pull/116.
> Add iconfinder

- util/qtxdg-iconfinder.cpp
It adds an per icon load time and a Total loadIcon() timing info.
> It adds loadIcon() timing measurements.

- qtxdg/xdgicon.cpp
- qtxdg/xdgicon.h
- xdgiconloader/xdgiconloader.cpp
- xdgiconloader/xdgiconloader_p.h
@tsujan please, consider this one as follow-up of #119 (my implementation of FollowColorScheme and (big?) optimization of pixmap generation)
> Icon follow color

- qtxdg/xdgdesktopfile.cpp
- qtxdg/xdgdesktopfile.h
> xdgdesktopfile: Actions handling

- xdgiconloader/xdgiconloader.cpp
Fixes https://github.com/lxde/lxqt/issues/1425 by using less private stuff.
> Fix symbolic SVG icons with Qt5.10

- xdgiconloader/xdgiconloader.cpp
Fixes https://github.com/lxde/lxqt/issues/1349
> Fixed a typo in searching gtk icon cache

- qtxdg/xdgdesktopfile.cpp
Introduced by commit 78b4fe3d.
> Prevent a possible container detach

- xdgiconloader/xdgiconloader.cpp
> Fixes pedantic warning

- src/qtxdg/xdgmenuwidget.cpp
Fixes https://github.com/lxqt/lxqt/issues/1512
> Fix menu-item drag url

- src/xdgiconloader/xdgiconloader.cpp
..and leave default colors for unknown/unsupported classes
Example... window-close from breeze:
- before
- after
> xdgiconloader: Support more classes for "FollowColors" icons

- src/qtxdg/xdgaction.cpp
> xdgaction: Set icon in updateIcon() only if needed

- src/qtxdg/xdgdesktopfile.cpp
QUrl::scheme() returns a lowercase scheme.
> XdgDesktopFile: Simplify scheme handling

- CMakeLists.txt
- examples/use-qtxdg/CMakeLists.txt
Removed the cmake version checks and just set it
> Set cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)

- src/qtxdg/xdgdesktopfile.cpp
IRC is great :)
But there is definitely no need to catch it twice
> Remove duplicate

- src/qtxdg/xdgautostart.cpp
- src/qtxdg/xdgdesktopfile.cpp
- src/qtxdg/xdgmenu.cpp
- src/qtxdg/xdgmenuapplinkprocessor.cpp
- src/qtxdg/xdgmenureader.cpp
- src/qtxdg/xdgmimetype.cpp
> Use qAsConst

- test/qtxdg_test.cpp
> test: Use qAsConst()

- src/qtxdg/xdgdesktopfile.cpp
> Removes not used helper function

- src/qtxdg/xdgicon.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/1139 and similar issues.
> Fixed icon cache with absolute paths

- src/qtxdg/xdgmimetype.h
> Remove obsolete qSwap

- src/xdgiconloader/xdgiconloader.cpp
Fixes https://github.com/lxqt/libqtxdg/issues/178
The SVG icon engine gives a too big pixmap with scale factors > 1, so that the final drawing will not be sharp if the real size is used. This patch scales down the pixmap to the actual size in order to get a sharp SVG icon, especially with non-integer scale factors.
Now, for the first time in LXQt, I get sharp SVG icons with `QT_SCALE_FACTOR=1.5`:) Before the patch:
After the patch:
NOTE: There's a comment in the patch that says, "The cause of this old behavior is unknown to me (@tsujan)." If you know the cause, please replace the comment!
> Sharp SVG icons with scale factors > 1

- src/qtxdg/xdgmenuapplinkprocessor.cpp
- src/qtxdg/xdgmenuapplinkprocessor.h
- src/qtxdg/xdgmenurules.cpp
- src/qtxdg/xdgmenurules.h
Use std::list. Code updated accordingly.
Using const_iterator where appropriated.
> Drop deprecated QLinkedList

- src/xdgiconloader/xdgiconloader.cpp
> Remove unused conditional code

- src/qtxdg/xdgmimeappsglibbackend.cpp
While using the code, I found out that `XdgMimeAppsGLibBackend::recommendedApps` and `XdgMimeAppsGLibBackend::apps` are not reliable: they may give wrong results, depending on the order of key values inside `~/.config/mimeapps.list`.
The reason is that one app may be removed from the recommended list due to a suspicious logic inside `XdgMimeAppsGLibBackend::recommendedApps`; and `XdgMimeAppsGLibBackend::apps` just adds that list to the list returned by `XdgMimeAppsGLibBackend::fallbackApps`.
Therefore, the current patch follows GLib exactly, by
1. Removing the suspicious logic from `XdgMimeAppsGLibBackend::recommendedApps` and also by
2. Directly using `g_app_info_get_all_for_type()` in `XdgMimeAppsGLibBackend::apps` (because it always guarantees a correct result).
NOTE: [GLib …
> Fixed (recommended) apps list given by GLib backend

- src/xdgiconloader/xdgiconloader.cpp
Previously (https://github.com/lxqt/libqtxdg/commit/ea10ca2bd14daf4641bd58d4963692f2df351710), the problem of distorted SVG icons with HDPI was solved by scaling down their big pixmaps but, later, Qt applied a better fix (https://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/image/qiconloader.cpp?id=d8ab719c0890195cfce0fb6d4c76b3664d6f3a9d). This patch just imports Qt's fix into LXQt.
Closes https://github.com/lxqt/libqtxdg/issues/224
> Qt fix for too big SVG icons with scale factors > 1

- src/qtxdg/xdgdesktopfile.cpp
- src/qtxdg/xdgmenulayoutprocessor.cpp
- test/qtxdg_test.cpp
- test/qtxdg_test.h
Good practice and a possible minor performance improvement.
> Use const references where possible

- src/xdgiconloader/xdgiconloader_p.h
> Drop Q_DECL_OVERRIDE

- src/tools/mat/defemailclientmatcommand.cpp
Handle arguments given without options.
> qtxdg-mat: Improve email client command line handling

- src/qtxdg/xdgdesktopfile.cpp
The code partially affected non-Exec keys too. This patch solves the problem by fully separating Exec keys from others.
Fixes https://github.com/lxqt/lxqt-panel/issues/1737
> Fixed a bug in supporting string literals in Exec keys

- src/xdgiconloader/xdgiconloader.cpp
Monitoring the GTK cache itself wasn't enough for showing real icons of newly installed apps (in Main Menu). Contrary to my expectations, the reason was that the cache was invalidated too late.
Here, the folder is monitored instead, and the cache is invalidated as soon as something happens inside the folder. It will be validated again when it's updated.
Closes https://github.com/lxqt/libqtxdg/issues/226
> Invalidate GTK icon cache as soon as icons are installed

- test/tst_xdgdesktopfile.cpp
Closes https://github.com/lxqt/libqtxdg/issues/302
> Fixed a test file after recent changes in Qt6

- src/qtxdg/xdgmenu.cpp
- src/qtxdg/xdgmenureader.cpp
- src/qtxdg/xdgmimetype.h
- src/xdgiconloader/xdgiconloader.cpp
- src/xdgiconloader/xdgiconloader_p.h
Closes https://github.com/lxqt/libqtxdg/issues/306
> Fix compilation with Qt ≥ 6.8
